/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <stdlib.h>
#include "tmp.hpp"

std::string lib::Grreeter::greeting() {
    return std::string("Hello, World!");
}
