/*
 * This C++ source file was generated by the Gradle 'init' task.
 */
#ifndef TMP_H
#define TMP_H

#ifdef _WIN32
#define TMP_EXPORT_FUNC __declspec(dllexport)
#else
#define TMP_EXPORT_FUNC
#endif

#include <string>

namespace lib {
    class Grreeter {
        public:
        std::string TMP_EXPORT_FUNC greeting();
    };
}

#endif
