/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include "tmp.hpp"
#include <cassert>

int main() {
    lib::Grreeter greeter;
    assert(greeter.greeting().compare("Hello, World!") == 0);
    return 0;
}
