/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include "app.hpp"
#include "tmp.hpp"
#include <iostream>
#include <stdlib.h>

std::string app::Greeter::greeting() { return std::string("Hello, World!"); }

int main () {
    app::Greeter greeter;
    lib::Grreeter grreeter;
    std::cout << greeter.greeting() << std::endl;
    std::cout << grreeter.greeting() << std::endl;
    return 0;
}
